### ISSUE TITLE
google_play_services_version

### ISSUE THREAD

**Issue by nareshkatta99** [varvet/BarcodeReaderSample#2]
java.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
                      at android.app.ActivityThread.access$800(ActivityThread.java:166)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5584)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                      at dalvik.system.NativeStart.main(Native Method)

 Caused by: java.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
                      at com.google.android.gms.common.zze.zzbs(Unknown Source)
                      at com.google.android.gms.common.zze.isGooglePlayServicesAvailable(Unknown Source)
                      at com.google.android.gms.common.zzc.isGooglePlayServicesAvailable(Unknown Source)
                      at com.google.android.gms.internal.zzsb.zzcs(Unknown Source)
                      at com.google.android.gms.internal.zzsb.zzd(Unknown Source)
                      at com.google.android.gms.internal.zzsb$1.zzd(Unknown Source)
                      at com.google.android.gms.internal.zzsb$5.zza(Unknown Source)
                      at com.google.android.gms.internal.zzsb.zza(Unknown Source)
                      at com.google.android.gms.vision.barcode.internal.client.zzd.zzchw(Unknown Source)
                      at com.google.android.gms.vision.barcode.internal.client.zzd.<init>(Unknown Source)
                      at com.google.android.gms.vision.barcode.BarcodeDetector$Builder.build(Unknown Source)

I checked entire project but there is no google_play_services_version anywhere

**Comment by daniellAlgar** [comment]
Hi Naresh-Katta. 

I'm on vacation at the moment so I'll check into this in a week or two.. But I surely state `compile 'com.google.android.gms:play-services:9.4.0'` in gradle so I'm not sure that you really "checked entire project". 

Have you installed Play Services in Android studio?

**Comment by nareshkatta99** [comment]
I installed Google play services revision 39.

**Comment by daniellAlgar** [comment]
@Naresh-Katta I'm really not able to do anything with that information... Did installing help?

**Comment by daniellAlgar** [comment]
@Naresh-Katta If you don't have any more info on this I would like to close the issue.

**Comment by nareshkatta99** [comment]
Sorry, Currently I stopped working on QR scanner, due to some problems. You can close this issue for sure.
